set(PROJECT_VERSION 0.1.0)
set(PROJECT_MAJOR_VERSION 0)
set(PROJECT_MINOR_VERSION 1)

if (APPLE)
    set_target_properties(${PROJECT_NAME} PROPERTIES
        MACOSX_BUNDLE TRUE
        MACOSX_BUNDLE_GUI_IDENTIFIER io.unionengine.un
        MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
        MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
        MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/app/Info.plist"
    )
    target_sources(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/app/Assets.xcassets)
    set_source_files_properties("${CMAKE_CURRENT_SOURCE_DIR}/app/Assets.xcassets" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
endif()